
//! Autogenerated weights for `pallet_parachain_bullposting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-03-11, STEPS: `5`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `BeefSlab`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/parachain-bullposting-runtime/parachain_bullposting_runtime.compact.compressed.wasm
// --pallet
// pallet_parachain_bullposting
// --extrinsic
// *
// --steps
// 5
// --repeat
// 2
// --template
// ./pallets/benchmarking/frame-weight-template.hbs
// --output
// ./pallets/bullposting/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_parachain_bullposting`.
pub trait WeightInfo {
	fn try_submit_post() -> Weight;
	fn try_submit_vote() -> Weight;
	fn try_update_vote() -> Weight;
	fn try_resolve_voting() -> Weight;
	fn try_end_post(x: u32, ) -> Weight;
}

/// Weights for `pallet_parachain_bullposting` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn try_submit_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3598`
		// Minimum execution time: 64_028_000 picoseconds.
		Weight::from_parts(88_146_000, 3598)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::VoteCounts` (r:1 w:1)
	/// Proof: `Bullposting::VoteCounts` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Voters` (r:1 w:1)
	/// Proof: `Bullposting::Voters` (`max_values`: None, `max_size`: Some(320050), added: 322525, mode: `MaxEncodedLen`)
	fn try_submit_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `323515`
		// Minimum execution time: 47_857_000 picoseconds.
		Weight::from_parts(53_619_000, 323515)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	fn try_update_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `564`
		//  Estimated: `4764`
		// Minimum execution time: 111_821_000 picoseconds.
		Weight::from_parts(124_623_000, 4764)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn try_resolve_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `516`
		//  Estimated: `3598`
		// Minimum execution time: 64_179_000 picoseconds.
		Weight::from_parts(72_356_000, 3598)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:0)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Voters` (r:1 w:1)
	/// Proof: `Bullposting::Voters` (`max_values`: None, `max_size`: Some(320050), added: 322525, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1000 w:1000)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1000 w:1000)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1000 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::VoteCounts` (r:1 w:1)
	/// Proof: `Bullposting::VoteCounts` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 2000]`.
	fn try_end_post(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `59370 + x * (243 ±0)`
		//  Estimated: `757225 + x * (1886 ±352)`
		// Minimum execution time: 96_548_000 picoseconds.
		Weight::from_parts(5_847_546_780, 757225)
			// Standard Error: 2_932_404
			.saturating_add(Weight::from_parts(19_116_376, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(807_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(x.into())))
			.saturating_add(T::DbWeight::get().writes(606_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
			.saturating_add(Weight::from_parts(0, 1886).saturating_mul(x.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn try_submit_post() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3598`
		// Minimum execution time: 64_028_000 picoseconds.
		Weight::from_parts(88_146_000, 3598)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::VoteCounts` (r:1 w:1)
	/// Proof: `Bullposting::VoteCounts` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Voters` (r:1 w:1)
	/// Proof: `Bullposting::Voters` (`max_values`: None, `max_size`: Some(320050), added: 322525, mode: `MaxEncodedLen`)
	fn try_submit_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `323515`
		// Minimum execution time: 47_857_000 picoseconds.
		Weight::from_parts(53_619_000, 323515)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1 w:1)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:1)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	fn try_update_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `564`
		//  Estimated: `4764`
		// Minimum execution time: 111_821_000 picoseconds.
		Weight::from_parts(124_623_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:1)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	fn try_resolve_voting() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `516`
		//  Estimated: `3598`
		// Minimum execution time: 64_179_000 picoseconds.
		Weight::from_parts(72_356_000, 3598)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Bullposting::Posts` (r:1 w:0)
	/// Proof: `Bullposting::Posts` (`max_values`: None, `max_size`: Some(133), added: 2608, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Voters` (r:1 w:1)
	/// Proof: `Bullposting::Voters` (`max_values`: None, `max_size`: Some(320050), added: 322525, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::Votes` (r:1000 w:1000)
	/// Proof: `Bullposting::Votes` (`max_values`: None, `max_size`: Some(113), added: 2588, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1000 w:1000)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1000 w:0)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Bullposting::VoteCounts` (r:1 w:1)
	/// Proof: `Bullposting::VoteCounts` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
	/// The range of component `x` is `[1, 2000]`.
	fn try_end_post(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `59370 + x * (243 ±0)`
		//  Estimated: `757225 + x * (1886 ±352)`
		// Minimum execution time: 96_548_000 picoseconds.
		Weight::from_parts(5_847_546_780, 757225)
			// Standard Error: 2_932_404
			.saturating_add(Weight::from_parts(19_116_376, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().reads(807_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(x.into())))
			.saturating_add(RocksDbWeight::get().writes(606_u64))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(x.into())))
			.saturating_add(Weight::from_parts(0, 1886).saturating_mul(x.into()))
	}
}